POST localhost:8080/events
Content-Type: application/json
Authorization:

{
  "name": "Gods of Metal Festival",
  "description": "A day of heavy metal music featuring top bands.",
  "location": "Madison Square Garden, New York",
  "date": "2025-08-15T14:00:00Z"
}
