DELETE localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY2tfc21pdGgiLCJleHAiOjE3NTI0MDUzNzEsInVzZXJJZCI6ImI2OTIzMjQ2LTYzY2YtNDYwNC1hMDE3LWI4YjBiYWE5NTNmYyJ9.6In75BhBQCLCRQmvHQ1DKsvQhSL2-GHD-znR5vRdi28
